CREATE TABLE [dbo].[Game_Pitching_Stats]
(
	[Id] INT IDENTITY,
	Game INT NOT NULL,
	Player INT NOT NULL,
	W INT NOT NULL DEFAULT 0,
	L INT NOT NULL DEFAULT 0,
	G INT NOT NULL DEFAULT 0,
	GS INT NOT NULL DEFAULT 0,
	CG INT NOT NULL DEFAULT 0,
	SHO INT NOT NULL DEFAULT 0,
	HLD INT NOT NULL DEFAULT 0,
	SV INT NOT NULL DEFAULT 0,
	SVO INT NOT NULL DEFAULT 0,
	[IP] DECIMAL NOT NULL DEFAULT 0,
	[H] INT NOT NULL DEFAULT 0,
	R INT NOT NULL DEFAULT 0,
	ER INT NOT NULL DEFAULT 0,
	HR INT NOT NULL DEFAULT 0,
	NP INT NOT NULL DEFAULT 0,
	HB INT NOT NULL DEFAULT 0,
	BB INT NOT NULL DEFAULT 0,
	IBB INT NOT NULL DEFAULT 0,
	SO INT NOT NULL DEFAULT 0

	CONSTRAINT PK_Game_Pitching_Stats PRIMARY KEY (Id),
	CONSTRAINT FK_Game_Pitching_Stats_Games_Game FOREIGN KEY (Game) REFERENCES Games(Id),
	CONSTRAINT FK_Game_Pitching_Stats_Players_Player FOREIGN KEY (Player) REFERENCES Players(Id)
)
