CREATE TABLE [dbo].[Gale_Pitching_Stats]
(
	[Id] INT IDENTITY,
	Game INT NOT NULL,
	Player INT NOT NULL,
	W INT NOT NULL,
	L INT NOT NULL,
	G INT NOT NULL,
	GS INT NOT NULL,
	CG INT NOT NULL,
	SHO INT NOT NULL,
	HLD INT NOT NULL,
	SV INT NOT NULL,
	SVO INT NOT NULL,
	IP DECIMAL NOT NULL,
	H INT NOT NULL,
	R INT NOT NULL,
	ER INT NOT NULL,
	HR INT NOT NULL,
	NP INT NOT NULL,
	HB INT NOT NULL,
	BB INT NOT NULL,
	IBB INT NOT NULL,
	SO INT NOT NULL,

	CONSTRAINT PK_Gale_Pitching_Stats PRIMARY KEY ([Id])
)
