CREATE TABLE [dbo].[Teams]
(
	[Id] INT IDENTITY,
	[Name] NVARCHAR(250) NOT NULL,
	[Owner] INT NOT NULL,
	City NVARCHAR(120) NOT NULL,
	Country INT NOT NULL,
	League INT NOT NULL,
	Season INT NOT NULL,
	CurrentDay INT NOT NULL DEFAULT 0,
	Budget BIGINT NOT NULL DEFAULT 0,
	Logo NVARCHAR(250),
	Color_1 NVARCHAR(6) NOT NULL,
	Color_2 NVARCHAR(6) NOT NULL,
	Color_3 NVARCHAR(6) DEFAULT 'FFFFFF',

	CONSTRAINT PK_Teams PRIMARY KEY (Id),
	CONSTRAINT FK_Teams_Users_Owner FOREIGN KEY (Owner) REFERENCES Users(Id),
	CONSTRAINT FK_Teams_Countries_Country FOREIGN KEY (Country) REFERENCES Countries(Id),
	CONSTRAINT FK_Teams_Leagues_League FOREIGN KEY (League) REFERENCES Leagues(Id),
)
