CREATE TABLE [dbo].[Teams]
(
	[Id] INT IDENTITY,
	[Name] NVARCHAR(250) NOT NULL,
	City NVARCHAR(120) NOT NULL,
	Country INT NOT NULL,
	Logo NVARCHAR(250),
	Color_1 NVARCHAR(6) NOT NULL,
	Color_2 NVARCHAR(6) NOT NULL,
	Color_3 NVARCHAR(6) DEFAULT 'FFFFFF',

  CONSTRAINT PK_Teams PRIMARY KEY (Id),
  CONSTRAINT UK_Teams_Name UNIQUE ([Name]),
  CONSTRAINT FK_Teams_Countries_Country FOREIGN KEY (Country) REFERENCES Countries(Id)
)
